2017-07-10 09:03:33,990 [40]ERROR LaiCai.Auth.Implement.Log4net - could not connect to redis Instance at 192.168.1.55:6379
2017-07-10 09:03:33,988 [42]ERROR LaiCai.Auth.Implement.Log4net - could not connect to redis Instance at 192.168.1.55:6379
2017-07-10 09:03:35,055 [42]ERROR LaiCai.Auth.Implement.Log4net - ServiceStack.Redis.RedisException: could not connect to redis Instance at 192.168.1.55:6379 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 192.168.1.55:6379
   在 System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
   在 System.Net.Sockets.Socket.Connect(String host, Int32 port)
   在 ServiceStack.Redis.RedisNativeClient.Connect()
   --- 内部异常堆栈跟踪的结尾 ---
   在 ServiceStack.Redis.RedisNativeClient.Connect()
   在 ServiceStack.Redis.RedisNativeClient.AssertConnectedSocket()
   在 ServiceStack.Redis.RedisNativeClient.SendCommand(Byte[][] cmdWithBinaryArgs)
   在 ServiceStack.Redis.RedisNativeClient.SendExpectData(Byte[][] cmdWithBinaryArgs)
   在 ServiceStack.Redis.RedisClient.GetValue(String key)
   在 ServiceStack.Redis.RedisClient.Get[T](String key)
   在 LaiCai.Auth.Implement.RedisCache.Get[T](String key) 位置 D:\code\src\02.WebApi\LaiCai.Auth\LaiCai.Auth\Implement\RedisCache.cs:行号 163
   在 LaiCai.Auth.Implement.ClientRepertory.GetById(String clientId) 位置 D:\code\src\02.WebApi\LaiCai.Auth\LaiCai.Auth\Implement\ClientRepertory.cs:行号 48
   在 LaiCai.Auth.Implement.TokenRepertory.<Isvalid>d__4.MoveNext() 位置 D:\code\src\02.WebApi\LaiCai.Auth\LaiCai.Auth\Implement\TokenRepertory.cs:行号 36
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 LaiCai.Auth.Implement.TokenRepertory.<CreateToken>d__5.MoveNext() 位置 D:\code\src\02.WebApi\LaiCai.Auth\LaiCai.Auth\Implement\TokenRepertory.cs:行号 57
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 LaiCai.Auth.Controllers.UserController.<Post>d__4.MoveNext() 位置 D:\code\src\02.WebApi\LaiCai.Auth\LaiCai.Auth\Controllers\UserController.cs:行号 83
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2017-07-10 09:03:35,055 [40]ERROR LaiCai.Auth.Implement.Log4net - ServiceStack.Redis.RedisException: could not connect to redis Instance at 192.168.1.55:6379 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 192.168.1.55:6379
   在 System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
   在 System.Net.Sockets.Socket.Connect(String host, Int32 port)
   在 ServiceStack.Redis.RedisNativeClient.Connect()
   --- 内部异常堆栈跟踪的结尾 ---
   在 ServiceStack.Redis.RedisNativeClient.Connect()
   在 ServiceStack.Redis.RedisNativeClient.AssertConnectedSocket()
   在 ServiceStack.Redis.RedisNativeClient.SendCommand(Byte[][] cmdWithBinaryArgs)
   在 ServiceStack.Redis.RedisNativeClient.SendExpectData(Byte[][] cmdWithBinaryArgs)
   在 ServiceStack.Redis.RedisClient.GetValue(String key)
   在 ServiceStack.Redis.RedisClient.Get[T](String key)
   在 LaiCai.Auth.Implement.RedisCache.Get[T](String key) 位置 D:\code\src\02.WebApi\LaiCai.Auth\LaiCai.Auth\Implement\RedisCache.cs:行号 163
   在 LaiCai.Auth.Implement.ClientRepertory.GetById(String clientId) 位置 D:\code\src\02.WebApi\LaiCai.Auth\LaiCai.Auth\Implement\ClientRepertory.cs:行号 48
   在 LaiCai.Auth.Implement.TokenRepertory.<Isvalid>d__4.MoveNext() 位置 D:\code\src\02.WebApi\LaiCai.Auth\LaiCai.Auth\Implement\TokenRepertory.cs:行号 36
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 LaiCai.Auth.Implement.TokenRepertory.<CreateToken>d__5.MoveNext() 位置 D:\code\src\02.WebApi\LaiCai.Auth\LaiCai.Auth\Implement\TokenRepertory.cs:行号 57
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 LaiCai.Auth.Controllers.UserController.<Post>d__4.MoveNext() 位置 D:\code\src\02.WebApi\LaiCai.Auth\LaiCai.Auth\Controllers\UserController.cs:行号 83
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2017-07-10 09:03:53,969 [42]ERROR LaiCai.Auth.Implement.Log4net - could not connect to redis Instance at 192.168.1.55:6379
2017-07-10 09:03:54,970 [42]ERROR LaiCai.Auth.Implement.Log4net - ServiceStack.Redis.RedisException: could not connect to redis Instance at 192.168.1.55:6379 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 192.168.1.55:6379
   在 System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
   在 System.Net.Sockets.Socket.Connect(String host, Int32 port)
   在 ServiceStack.Redis.RedisNativeClient.Connect()
   --- 内部异常堆栈跟踪的结尾 ---
   在 ServiceStack.Redis.RedisNativeClient.Connect()
   在 ServiceStack.Redis.RedisNativeClient.AssertConnectedSocket()
   在 ServiceStack.Redis.RedisNativeClient.SendCommand(Byte[][] cmdWithBinaryArgs)
   在 ServiceStack.Redis.RedisNativeClient.SendExpectData(Byte[][] cmdWithBinaryArgs)
   在 ServiceStack.Redis.RedisClient.GetValue(String key)
   在 ServiceStack.Redis.RedisClient.Get[T](String key)
   在 LaiCai.Auth.Implement.RedisCache.Get[T](String key) 位置 D:\code\src\02.WebApi\LaiCai.Auth\LaiCai.Auth\Implement\RedisCache.cs:行号 163
   在 LaiCai.Auth.Implement.ClientRepertory.GetById(String clientId) 位置 D:\code\src\02.WebApi\LaiCai.Auth\LaiCai.Auth\Implement\ClientRepertory.cs:行号 48
   在 LaiCai.Auth.Implement.TokenRepertory.<Isvalid>d__4.MoveNext() 位置 D:\code\src\02.WebApi\LaiCai.Auth\LaiCai.Auth\Implement\TokenRepertory.cs:行号 36
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 LaiCai.Auth.Implement.TokenRepertory.<CreateToken>d__5.MoveNext() 位置 D:\code\src\02.WebApi\LaiCai.Auth\LaiCai.Auth\Implement\TokenRepertory.cs:行号 57
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 LaiCai.Auth.Controllers.UserController.<Post>d__4.MoveNext() 位置 D:\code\src\02.WebApi\LaiCai.Auth\LaiCai.Auth\Controllers\UserController.cs:行号 83
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--认证中心2017-07-10 09:56:00,173 [10]ERROR LaiCai.Auth.Implement.Log4net - could not connect to redis Instance at 192.168.1.55:6379
2017-07-10 09:56:01,236 [10]ERROR LaiCai.Auth.Implement.Log4net - ServiceStack.Redis.RedisException: could not connect to redis Instance at 192.168.1.55:6379 ---> System.Net.Sockets.SocketException: 由于目标计算机积极拒绝，无法连接。 192.168.1.55:6379
   在 System.Net.Sockets.Socket.Connect(IPAddress[] addresses, Int32 port)
   在 System.Net.Sockets.Socket.Connect(String host, Int32 port)
   在 ServiceStack.Redis.RedisNativeClient.Connect()
   --- 内部异常堆栈跟踪的结尾 ---
   在 ServiceStack.Redis.RedisNativeClient.Connect()
   在 ServiceStack.Redis.RedisNativeClient.AssertConnectedSocket()
   在 ServiceStack.Redis.RedisNativeClient.SendCommand(Byte[][] cmdWithBinaryArgs)
   在 ServiceStack.Redis.RedisNativeClient.SendExpectData(Byte[][] cmdWithBinaryArgs)
   在 ServiceStack.Redis.RedisClient.GetValue(String key)
   在 ServiceStack.Redis.RedisClient.Get[T](String key)
   在 LaiCai.Auth.Implement.RedisCache.Get[T](String key) 位置 D:\code\src\02.WebApi\LaiCai.Auth\LaiCai.Auth\Implement\RedisCache.cs:行号 163
   在 LaiCai.Auth.Implement.ClientRepertory.GetById(String clientId) 位置 D:\code\src\02.WebApi\LaiCai.Auth\LaiCai.Auth\Implement\ClientRepertory.cs:行号 48
   在 LaiCai.Auth.Implement.TokenRepertory.<Isvalid>d__4.MoveNext() 位置 D:\code\src\02.WebApi\LaiCai.Auth\LaiCai.Auth\Implement\TokenRepertory.cs:行号 36
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 LaiCai.Auth.Implement.TokenRepertory.<CreateToken>d__5.MoveNext() 位置 D:\code\src\02.WebApi\LaiCai.Auth\LaiCai.Auth\Implement\TokenRepertory.cs:行号 57
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 LaiCai.Auth.Controllers.UserController.<Post>d__4.MoveNext() 位置 D:\code\src\02.WebApi\LaiCai.Auth\LaiCai.Auth\Controllers\UserController.cs:行号 83
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
--认证中心--认证中心2017-07-10 11:00:26,398 [12]ERROR LaiCai.Auth.Implement.Log4net - acai.com的令牌过期时间没有设置
--认证中心2017-07-10 11:00:59,323 [10]ERROR LaiCai.Auth.Implement.Log4net - acai.com的令牌过期时间没有设置
--认证中心2017-07-10 11:01:38,928 [10]ERROR LaiCai.Auth.Implement.Log4net - acai.com的令牌过期时间没有设置
2017-07-10 11:02:23,992 [11]ERROR LaiCai.Auth.Implement.Log4net - acai.com的令牌过期时间没有设置
--认证中心2017-07-10 11:07:18,993 [26]ERROR LaiCai.Auth.Implement.Log4net - 刷新令牌设置不正确
2017-07-10 11:52:30,759 [5]ERROR LaiCai.Auth.Implement.Log4net - System.OperationCanceledException: 已取消该操作。
   在 System.Threading.CancellationToken.ThrowOperationCanceledException()
   在 System.Net.Http.HttpContentExtensions.<ReadAsAsyncCore>d__0`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.ModelBinding.FormatterParameterBinding.<ExecuteBindingAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.HttpActionBinding.<ExecuteBindingAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2017-07-10 11:53:07,852 [8]ERROR LaiCai.Auth.Implement.Log4net - System.Exception: 非法访问
   在 LaiCai.Auth.Implement.TokenRepertory.<UpdateTokenByRefresh>d__9.MoveNext() 位置 D:\code\src\02.WebApi\LaiCai.Auth\LaiCai.Auth\Implement\TokenRepertory.cs:行号 270
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 LaiCai.Auth.Controllers.TokenController.<Post>d__3.MoveNext() 位置 D:\code\src\02.WebApi\LaiCai.Auth\LaiCai.Auth\Controllers\TokenController.cs:行号 80
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2017-07-10 11:55:33,347 [6]ERROR LaiCai.Auth.Implement.Log4net - System.Exception: 非法访问
   在 LaiCai.Auth.Implement.TokenRepertory.<UpdateTokenByRefresh>d__9.MoveNext() 位置 D:\code\src\02.WebApi\LaiCai.Auth\LaiCai.Auth\Implement\TokenRepertory.cs:行号 270
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 LaiCai.Auth.Controllers.TokenController.<Post>d__3.MoveNext() 位置 D:\code\src\02.WebApi\LaiCai.Auth\LaiCai.Auth\Controllers\TokenController.cs:行号 80
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2017-07-10 11:55:37,674 [5]ERROR LaiCai.Auth.Implement.Log4net - System.Exception: 非法访问
   在 LaiCai.Auth.Implement.TokenRepertory.<UpdateTokenByRefresh>d__9.MoveNext() 位置 D:\code\src\02.WebApi\LaiCai.Auth\LaiCai.Auth\Implement\TokenRepertory.cs:行号 270
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 LaiCai.Auth.Controllers.TokenController.<Post>d__3.MoveNext() 位置 D:\code\src\02.WebApi\LaiCai.Auth\LaiCai.Auth\Controllers\TokenController.cs:行号 80
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
2017-07-10 11:57:14,769 [29]ERROR LaiCai.Auth.Implement.Log4net - System.OperationCanceledException: 已取消该操作。
   在 System.Threading.CancellationToken.ThrowOperationCanceledException()
   在 System.Net.Http.HttpContentExtensions.<ReadAsAsyncCore>d__0`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.ModelBinding.FormatterParameterBinding.<ExecuteBindingAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.HttpActionBinding.<ExecuteBindingAsyncCore>d__0.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()
